networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - dev
    
  backend:
    build:
      context: ./backend
    depends_on:
      - env
    networks:
      - dev
  
  frontend:
    build:
      context: ./frontend
    depends_on:
      - env
    networks:
      - dev
  
  env:
    volumes:
    - ./root/.env:/root/wsforum/backend/.env
    environment:
      - DBROOT=${DBROOT}
      - HASH_KEY=${HASH_KEY}
    env_file:
      - .env
    networks: dev
